/**
 * Steps 13–15: Simulation & external verification for Crash.
 *   13. Simulation Pass 1 — multi-stream chi-squared + Fisher's combined test
 *   14. Simulation Pass 2 — casino seed distribution test
 *   15. drand API Verification — reads pinned outputs/drand-api-verification.json
 *
 * Steps 13–14 read from outputs/simulation-results.json.
 * Step 15 reads from outputs/drand-api-verification.json (generated by npm run timing).
 */

import * as fs   from 'fs';
import * as path from 'path';
import type { VerifyContext, StepResult } from './context';

interface StreamResult {
  chi2: number;
  df: number;
  pValue: number;
}

interface Pass1Results {
  totalRounds: number;
  streams: number;
  roundsPerStream: number;
  targets?: number[];
  streamResults: StreamResult[];
  fisherCombined: { statistic: number; df: number; pValue: number };
  lag1R: number;
  lag1Z: number;
  runsP: number;
  simulatedRTP: number;
  perTargetRTP?: Record<string, number>;
  theoreticalMaxRTP: number;
}

interface Pass2Results {
  seedsTested: number;
  noncesPerSeed: number;
  chi2Fails: number;
  meanCasinoRTP: number;
}

interface SimulationResults {
  pass1_fresh_seeds: Pass1Results;
  pass2_casino_seeds: Pass2Results;
}

export function run(ctx: VerifyContext): StepResult[] {
  const results: StepResult[] = [];

  const simPath = path.join(ctx.outputsDir, 'simulation-results.json');
  if (!fs.existsSync(simPath)) {
    results.push({
      step: 13, name: 'Simulation Pass 1',
      status: 'FAIL', detail: 'simulation-results.json not found — run npm run simulate first',
    });
    results.push({
      step: 14, name: 'Simulation Pass 2',
      status: 'FAIL', detail: 'simulation-results.json not found',
    });
    return results;
  }

  const sim: SimulationResults = JSON.parse(fs.readFileSync(simPath, 'utf8'));

  // Step 13: Pass 1 — multi-stream chi-squared with Fisher's combined test
  {
    const p1 = sim.pass1_fresh_seeds;
    const fisherPass = p1.fisherCombined.pValue >= 0.01;
    const serialPass = Math.abs(p1.lag1Z) < 3 && p1.runsP >= 0.01;
    const allPass = fisherPass && serialPass;

    // Build RTP summary
    let rtpSummary: string;
    if (p1.perTargetRTP && p1.targets) {
      rtpSummary = p1.targets.map(t => `@${t}×=${(p1.perTargetRTP![String(t)] * 100).toFixed(4)}%`).join(', ');
    } else {
      rtpSummary = `simRTP=${(p1.simulatedRTP * 100).toFixed(4)}%`;
    }

    const belowAlpha = p1.streamResults.filter(r => r.pValue < 0.01).length;

    results.push({
      step: 13,
      name: 'Simulation Pass 1',
      status: allPass ? 'PASS' : 'FAIL',
      detail: `${p1.totalRounds.toLocaleString()} rounds (${p1.streams} streams × ${p1.roundsPerStream.toLocaleString()}) — Fisher's combined: p=${p1.fisherCombined.pValue.toFixed(4)} (${belowAlpha}/${p1.streams} streams below α=0.01) | lag1Z=${p1.lag1Z.toFixed(3)}, runsP=${p1.runsP.toFixed(4)} | ${rtpSummary}`,
    });
  }

  // Step 14: Pass 2 — casino seeds
  {
    const p2 = sim.pass2_casino_seeds;
    // With drand, cherry-picking server seeds is ineffective because the outcome
    // also depends on unpredictable drand randomness. This step checks that
    // casino seeds produce expected distributions when paired with random drand values.
    // Threshold: expected failures under H₀ = seeds × α. Binomial upper bound.
    const expectedFails = p2.seedsTested * 0.01;
    const threshold = Math.ceil(expectedFails + 3 * Math.sqrt(expectedFails * 0.99));
    const pass = p2.chi2Fails <= threshold;

    results.push({
      step: 14,
      name: 'Simulation Pass 2 (Casino Seeds)',
      status: pass ? 'PASS' : 'FAIL',
      detail: `${p2.seedsTested} casino seeds × ${p2.noncesPerSeed} random drand values — ${p2.chi2Fails} chi-squared failures (expected ≤${threshold} under H₀) | meanRTP=${(p2.meanCasinoRTP * 100).toFixed(4)}%`,
    });
  }

  // Step 15: drand API Verification — reads pinned artifact
  {
    const drandPath = path.join(ctx.outputsDir, 'drand-api-verification.json');
    if (!fs.existsSync(drandPath)) {
      results.push({
        step: 15,
        name: 'drand API Signature Verification',
        status: 'FAIL',
        detail: 'drand-api-verification.json not found — run npm run timing first (requires internet)',
      });
    } else {
      const drand = JSON.parse(fs.readFileSync(drandPath, 'utf8'));
      const total = drand.totalRounds as number;
      const passed = drand.passed as number;
      const failed = drand.failed as number;

      results.push({
        step: 15,
        name: 'drand API Signature Verification',
        status: failed === 0 ? 'PASS' : 'FAIL',
        detail: `${passed}/${total} drand signatures matched byte-for-byte against api.drand.sh (chain: quicknet) — ${failed} failures`,
      });
    }
  }

  return results;
}
